#!/bin/sh -e

systemctl enable  device-tree-overlay.service
systemctl enable  udmabuf.service
systemctl enable  zptty.service

systemctl start   device-tree-overlay.service
systemctl start   udmabuf.service
systemctl start   zptty.service


